[workspace]
members = ["fiber-lib", "fiber-bin"]
resolver = "2"
default-members = [
    "fiber-bin",
    "fiber-lib"
]
[profile.release]
panic = "abort"
overflow-checks = true

[profile.dev]
panic = "abort"

[profile.quick_test]
inherits = "test"
opt-level = 3
debug = false

[patch.crates-io]
blake2b-rs = { git = "https://github.com/Officeyutong/blake2b-rs", rev = "f018d62" }
